### ISSUE TITLE
Mic icon seems confusing to me

### ISSUE THREAD

**Issue by viktorlesyk** [alyssaxuu/screenity#11]
![Screenshot 2020-11-22 133444](https://user-images.githubusercontent.com/74859706/99902596-9c759e00-2cc7-11eb-80ee-20c56af48d08.jpg)

Does the mic icon confuse anyone as well? What if we change the "mic off" icon to red crossed? Just like the google meet has
![image](https://user-images.githubusercontent.com/74859706/99902653-1017ab00-2cc8-11eb-9199-bff5ea9d0175.png)

Because the blue icon makes me think the mic is on and working and the white is off.

**Comment by alyssaxuu** [comment]
Hmm maybe, the issue with red though is that it stands out a lot & with the controls visible all the time in the recording (unless you set the controls to show only on hover) it feels a bit too much:

<img width="459" alt="Screen Shot 2020-11-22 at 12 45 27 PM" src="https://user-images.githubusercontent.com/7581348/99902782-9af4a780-2cc0-11eb-84ee-b4dbe87a2961.png">

Having the pause button blue and the mic/system audio red also looks weird. Plus the "toggled" state for the tools has the blue background anyway. Maybe it would be better if instead of showing the crossed out icons in the blue, the icons were normal, showing you that the microphone and system audio are enabled (just like how it works with the other tools)? Not sure.

**Comment by viktorlesyk** [comment]
May be) Let's see if it confuses anyone except me) If yes, I think it's worth trying to make it more intuitive to understand, whether the mic is recording or not.

**Comment by gregkonush** [comment]
I agree that the microphone icon is confusing, I think it should be flipped, or at least maybe it should have a tooltip to indicate that is in fact recording.

**Comment by megaroeny** [comment]
I agree as well. I think what is more common with controls like these, is the icon represents the current state, not the action leading to it.

**Comment by DannyFeliz** [comment]
I got confused by the mic icon the first time I used, I thought it wasn't recording the mic.

**Comment by alyssaxuu** [comment]
I switched the icons in the 2.2.2 release.

**Comment by megaroeny** [comment]
> I switched the icons in the 2.2.2 release.

There's one caveat to this - with push to talk Enabled, the mic should show the muted (blue crossed) icon until Ctrl + M is pressed to open the mic, which becomes the regular mic icon that's white.

Does that make sense?

**Comment by alyssaxuu** [comment]
> > I switched the icons in the 2.2.2 release.
> 
> There's one caveat to this - with push to talk Enabled, the mic should show the muted (blue crossed) icon until Ctrl + M is pressed to open the mic, which becomes the regular mic icon that's white. Currently, it's the opposite 😅
> 
> Does that make sense?

I'm not sure what you mean - currently with push to talk it simply toggles the microphone icon from blue + not crossed (enabled) and white + crossed (disabled), which I think makes sense, as when you're holding Ctrl + M it "highlights" to represent that you're speaking.

![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/7581348/100108573-36298080-2e6b-11eb-981a-35fdeab19ad7.gif)

**Comment by megaroeny** [comment]
Oop!! My extension didn't update, sorry! I'm turning on Developer Mode so I can manually update my extensions now. 😂
