### ISSUE TITLE
MP4 export not working?

### ISSUE THREAD

**Issue by tomas** [alyssaxuu/screenity#114]
Hi, just installed the extension from the Chrome Web Store on a Chromebook. Everything seems to work OK but when choosing MP4 as the export format and clicking on Download doesn't seem to work-- no transcoding seems to happen and the video gets immediately downloaded. The file does have a .mp4 extension when inspecting the file type I get `webm`. 

Also tried using using the "Trim video" option, but if I hit the "Apply" button, and then "Download" then I get an empty `mp4` file.

Is this a known issue?

**Comment by alyssaxuu** [comment]
Yes, this is known issue (#7 & #9). It would require processing the video through a server which would cost money, but the extension is free. I've also tried processing through a client-side version of FFMPEG, but it won't work with audio due to the VP8 format, and it still takes a long time to process. I will keep looking for a solution.

**Comment by tomas** [comment]
I see.

If that's the case then what's the point of showing MP4 as an export option? 

As for the audio issue, in my case I want to produce short videos without any audio, so running ffmpeg.wasm wouldn't pose an issue. :)

**Comment by KazimirPodolski** [comment]
Why the issue is closed then? The buttons are there but silently doesn't work.

**Comment by alyssaxuu** [comment]
> Why the issue is closed then? The buttons are there but silently doesn't work.

This issue is from an older version of Screenity. In the current version, MP4 export should work using WebCodecs and native MP4 recording support where available.

If you’re still having trouble, could you let me know which version of Screenity you’re using and what exactly happens when you try to export. For example, whether you see any warning, modal or banner, whether the button is disabled, or whether nothing happens at all?

You can also email me at support@screenity.io with the troubleshooting ZIP file so I can take a closer look. To download it, open the Screenity extension, click the three dots in the top-right corner, and select “Download data for troubleshooting”. It doesn’t contain any video or audio, only technical information and logs that can help me see what’s going wrong.

**Comment by KazimirPodolski** [comment]
> If you’re still having trouble, could you let me know which version of Screenity you’re using and what exactly happens when you try to export. For example, whether you see any warning, modal or banner, whether the button is disabled, or whether nothing happens at all?

In the latest Chome extension as of yesterday, export to MP4 always exports WEBM instead.

**Comment by alyssaxuu** [comment]
> > If you’re still having trouble, could you let me know which version of Screenity you’re using and what exactly happens when you try to export. For example, whether you see any warning, modal or banner, whether the button is disabled, or whether nothing happens at all?
> 
> In the latest Chome extension as of yesterday, export to MP4 always exports WEBM instead.

If that’s happening, then it’s definitely not expected and I’d like to get it fixed.

Could you email the troubleshooting ZIP to support@screenity.io? It contains the technical information I need to determine why MP4 isn’t being used on your setup, for example whether Screenity is falling back to another recording or export path. Once I can identify the cause, I can work out the appropriate fix.
