### ISSUE TITLE
Save as mp4 without converting to mp4?

### ISSUE THREAD

**Issue by zheoreh** [alyssaxuu/screenity#133]
Hi @alyssaxuu 
Why here: https://github.com/alyssaxuu/screenity/blob/master/js/videoeditor.js#L126
you don't use `convertStreams(superBuffer, "mp4");` ?

**Comment by zheoreh** [comment]
Maybe because of this hack? https://github.com/alyssaxuu/screenity/blob/5272fded700a566d00ea5a7339cbab3a177e318d/js/camera.js#L64

**Comment by prashant-shahi** [comment]
@zheoreh From my previous experience, I found `convertStreams(superBuffer, "mp4")` to be a very slow operation. It will take minutes for ~20 seconds long video.
That's why in screenity, it "fake saves" WebM as an MP4 which gets done in seconds.
The generated file should run without any problem in "most" video players.

**Comment by alyssaxuu** [comment]
Fixed in the new MV3 version.
