### ISSUE TITLE
Converting to Manifest V3

### ISSUE THREAD

**Issue by EkremPolat** [alyssaxuu/screenity#166]
Hello Alyssa!
Do you consider converting the chrome extension to Manifest V3? If you do, when are you planning to do that? Thank you so much for your effort!

**Comment by aswinkp** [comment]
There is already an open issue #152. @alyssaxuu mentioned that she will be porting in the coming months (possibly before the end of 2022)  🤞

**Comment by alyssaxuu** [comment]
Sorry it's taking so long, I've been struggling to figure out a direction for the product itself. I think if I convert to MV3 I would like to add new features and functionality, instead of having it be the exact same thing.

**Comment by alyssaxuu** [comment]
> @alyssaxuu Hi, any update?

I started working on the new version last month, it's been rough. I'm pretty sure no other screen recorder has ported to MV3 yet (you can check, Loom, Screencastify, Vidyard, and many others are still on MV2) because of all the limitations and changes in MV3, which makes it practically impossible to have a screen recorder working as an extension.

The main blocker has been the fact that the background becomes a service worker in MV3, which has no access to the DOM, so I can't start a MediaRecorder instance from there. If you start it from the tab, then as soon as that tab is closed, the recording ends (which is not ideal). Other options involve using a separate window, or having a tab open automatically to record (again, it cannot be closed). There's also the chrome.offscreen API which I also tried out as an option (to access the DOM from the background), but also hit a wall, regardless I'd have to wait for the API to be available in the new version of Chrome, it's only in Canary at the moment. I did actually manage to do something a bit hacky and make it work in a way that the user cannot accidentally stop the recording, and it doesn't require external windows, although I'd like to develop the project further along before sharing anything.

Either way, it will take a while to develop. I am building everything from the ground up, and I am hoping to add a lot of new features, including cloud storage (as an additional paid option, I still will keep a 100% free and open source version of the app), sharing, captions, and more.

**Comment by ABitShift** [comment]
Hi @alyssaxuu,
First of all, thank you for sharing to the community this awesome extension, freely and open sourced :heart: 
We are looking to inject content as you did, but using V3 [new scripting API](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript), if you succeed interacting with `main` world, would you please mind sharing the current branch you're working on?

**Comment by ABitShift** [comment]
> Hi @alyssaxuu, First of all, thank you for sharing to the community this awesome extension, freely and open sourced heart We are looking to inject content as you did, but using V3 [new scripting API](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript), if you succeed interacting with `main` world, would you please mind sharing the current branch you're working on?

For anyone looking for this technique, @alyssaxuu did it in another project: https://github.com/alyssaxuu/omni/tree/master/src

**Comment by shunMB** [comment]
Hi @alyssaxuu, any update?

**Comment by alyssaxuu** [comment]
I'm working on it, my plan is to do a bit of a modular release, trying to ship a first MV3 version with feature parity to the current extension, and add new features from there. Although it's still going to take some time as it's a bit of an overhaul.

Shared a sneak peek on Twitter if curious: https://twitter.com/alyssaxuu/status/1646897599536873474

I'm also writing about the process [on my newsletter](https://alyssax.substack.com/p/rebuilding-screenity-from-zero-and), with more specific plans.

**Comment by alyssaxuu** [comment]
Good news, the extension is finally ready, and I will be releasing it to the public in a week or so.

Here's the extension in use: [https://twitter.com/alyssaxuu/status/1720459565324542401](https://twitter.com/alyssaxuu/status/1720459565324542401)

If anyone is interested in getting private access to the extension (for helping with testing / feedback), please do reach out!

**Comment by aswinkp** [comment]
@alyssaxuu I'm eagerly awaiting this release 🤞 
Once it's released, I'm looking forward to contributing in any way I can.

**Comment by alyssaxuu** [comment]
I've finally released the new MV3 version of Screenity in the [Chrome Store](https://chromewebstore.google.com/detail/screenity-screen-recorder/kbbdabhdfibnancpjfhlkhafgdilcnji), and also updated the codebase here. If you'd like to know more about the changes, you can check out [this article I wrote](https://help.screenity.io/getting-started/77KizPC8MHVGfpKpqdux9D/what%E2%80%99s-changed-in-the-new-version-of-screenity/bDtvcwAtw9PPesQeNH4zjE). Hope you like it!
