### ISSUE TITLE
can't rec

### ISSUE THREAD

**Issue by leadra** [alyssaxuu/screenity#202]
![A01](https://github.com/alyssaxuu/screenity/assets/67009996/55b6144a-fdc6-451a-afdb-2557d6227ca9)
always this window

更新版本後，一直出現無權限，點選啟用只會一直跳一樣視窗，已經開啟攝影機權限了
![image](https://github.com/alyssaxuu/screenity/assets/67009996/084ef07a-6ae7-4b94-a294-873e3ce55fa4)

原本可以直接錄製分頁TAB的功能，可以直接選擇嗎?
原本可以點錄製馬上開始錄影，現在需要點選錄製>選擇錄製螢幕or瀏覽器視窗>分享音訊打勾>才開始錄影

Cent Browser
版本 5.0.1002.354 (正式版本) (32 位元) (Chromium 102.0.5005.167)

**Comment by alyssaxuu** [comment]
Oh no, I'm sorry. I think this might be an issue with Cent Browser. The expected behavior for this specific modal you're seeing is asking for extension permissions to allow recording the screen (not camera or microphone), but it might be specific to Chrome:

https://github.com/alyssaxuu/screenity/assets/7581348/ee204bf9-75ab-40ef-92b4-6dc5fdb8fe29

I can try to investigate how to make it work on Cent Browser, but I can't skip this step as otherwise it won't allow you to capture the screen.

As per tab recording, you can select the "Tab area" recording (the 2nd tab in the popup), and turn off the switch for "Set an area to record in". This will allow you to record the tab automatically with audio, and it will remember for next time as well.

**Comment by leadra** [comment]
old version: OK~sucess
chrome use
 turn off the switch for "Set an area to record in".
sucess

thanks for teach
感謝您的告知!
