### ISSUE TITLE
Load extension only on click

### ISSUE THREAD

**Issue by anilshanbhag** [alyssaxuu/screenity#216]
I have an enhancement suggestion. It looks like Screenity is adding an iframe to each tab. 

<img width="749" alt="Screenshot 2024-02-10 at 12 49 03 PM" src="https://github.com/alyssaxuu/screenity/assets/703656/747b6761-b56f-42ce-b5aa-7a63f36ed6d9">

<img width="967" alt="Screenshot 2024-02-10 at 12 50 39 PM" src="https://github.com/alyssaxuu/screenity/assets/703656/707690a9-054f-4eda-9616-a10f8fa448e7">

Loom doesn't seem to insert an iframe into each tab. It would be good to ensure the extension doesn't take any resources until it is clicked on.

**Comment by alyssaxuu** [comment]
True, I could have the iframe load after the extension is opened. I think I had it added beforehand because I was having issues getting the camera and microphone permissions (which is done through the iframe), and it added an extra delay. I am still having to add extra elements to the DOM (just like Loom does) anyway to be able to toggle the extension.

In that same details page though (chrome://extensions/?id=kbbdabhdfibnancpjfhlkhafgdilcnji), under Side access, you do have the option to make it only access the tab and inject on click, which can be a workaround for now.

**Comment by alyssaxuu** [comment]
Fixed in the [latest release](https://github.com/alyssaxuu/screenity/releases/tag/v3.1.7), now the iframes only load after clicking on the extension button. Will go live on the Chrome Store in a day or so.
