### ISSUE TITLE
I can't see my page

### ISSUE THREAD

**Issue by shijunwen** [alyssaxuu/screenity#22]
![image](https://user-images.githubusercontent.com/33819581/100306037-63963b80-2fdd-11eb-8219-d256b71d3e35.png)
![image](https://user-images.githubusercontent.com/33819581/100306061-7446b180-2fdd-11eb-9890-ff0beecf23ba.png)

**Comment by alyssaxuu** [comment]
Oh I think I know what this is caused by. Basically in order to detect document height changes (for example in infinite scrolling websites like Twitter) to expand the drawing area, the body must have an unset height. So I automatically set the body height to unset, which must break certain layouts. I'm not sure what workaround there could be, but I'll definitely look into it.

**Comment by alyssaxuu** [comment]
Going to be merging with #25 as it's the same issue.

**Comment by alyssaxuu** [comment]
I just fixed it :)

**Comment by shijunwen** [comment]
Looking forward to your update

**Comment by alyssaxuu** [comment]
> Looking forward to your update

It just went live on the Chrome Store.
