### ISSUE TITLE
Webpage Compressed on Video Start

### ISSUE THREAD

**Issue by histteacher** [alyssaxuu/screenity#25]
Rare issue...?

Website gets compressed when using Screenity.

Website (Google webapp) contains split.js.  Other recording tools (ex: Loom / ScreenCastify) work. Pen function still appears to work.

![7F0CAB66-C174-4B39-911F-C10A78576FC0](https://user-images.githubusercontent.com/38225776/100451026-b414a400-3084-11eb-897e-049dafc93ca2.GIF)

**Comment by alyssaxuu** [comment]
Yeah I should definitely do something about this. Basically in order to detect document height changes (for example in infinite scrolling websites like Twitter) to expand the drawing area, the body must have an unset height. So I automatically set the body height to unset, which in this case breaks the layout. I'm not sure what I could do about it :/ Do I just remove the resize observer and thus make it unable for people to draw on infinite scrolling websites? Maybe there's a way I could detect if a page needs the height to be set or not, I'll look into it.

**Comment by alyssaxuu** [comment]
Actually could you share a link so I can recreate the issue?

**Comment by histteacher** [comment]
It's Google App I created.  First time building something this large...
the webpage is labeled zMain.

Here is the Google Slide with links:
https://docs.google.com/presentation/d/1Y5FWquTFkbTxNlCCLpL2cH_xoIMcTb_GvpHY3HlyW1w/edit#slide=id.p

I also posted it on [TpT](https://www.teacherspayteachers.com/Product/Rubric-Hero-6027112?st=52948e021f339b994de3061e5b1470de)

Sorry for any confusion with my site.  The base page is zMain in the App Script Editor. 
https://www.teacherspayteachers.com/Product/Rubric-Hero-6027112?st=52948e021f339b994de3061e5b1470de

Here is the URL to the slides that

**Comment by alyssaxuu** [comment]
All right, I see. I just fixed the issue by declaring some specific websites that use infinite scrolling where the body doesn't change dimensions. It might not be the perfect solution but I'll investigate further, at least the websites shouldn't break anymore though :) 

Look for version 2.3.3 which I just published in the Chrome Store, should go live soon.
