### ISSUE TITLE
While recording larger videos, it starts to behave abnormally

### ISSUE THREAD

**Issue by meticulousCraftman** [alyssaxuu/screenity#35]
I'm on Chrome Version 86.0.4240.111 (Official Build) (64-bit).
I'm using screenity to record my work primarily between 2 windows (Chrome @ localhost:3000 and Visual Studio Code Editor).

There are multiple problems that I face, here's the list:

1. If I have 3 tabs open, the webcam feed will only be visible in 2 tabs. Sometimes it does show on all 3. Sometimes it doesn't.

2. The moment you hit **Start Recording** button on the extension, a window pops up asking you to select what is it that you want to record, Entire Screen or a specific application or a chrome tab. After doing 2-3 recordings, this option stops coming up and it defaults to recording only my current chrome tab. I tried restarting chrome, but that window doesn't reappear.

3. When recording long videos (more than 10 minutes), the page that opens up when you hit **Stop Recording** button on the extension has a video player in it. The video player only plays the last part of the screen recording (about 1-2 minutes) and that's all you can see. When I leave the page open for a couple of minutes it then shows me the entire recorded video.

BTW you have created an amazing tool! I love using it! 👍🏼

**Comment by alyssaxuu** [comment]
Hmm, let's see.

For 1, I might have to do some testing. Currently the controls and camera get injected automatically when you make a new tab, update the current tab, or switch to an already existing tab. Maybe I need to check for some other things (e.g. clicking on a link that opens a new tab), that said, it could also be due to the page itself preventing injection. There's certain pages (new tab page, so Google homepage or whichever you have set, the Chrome Web Store, and internal Chrome pages like the settings) where I cannot inject content, so would be good to make sure you aren't running into this problem first.

2, that's very strange, are you sure you have the "Desktop" option set in the popup when you want to do that instead of "Tab only"? I will investigate anyway, maybe there's some sort of sync issue.

3, this in particular appears to be an important issue. I am using a pretty high end device and I can make long recordings without a problem whatsoever, but I believe there's something about the RAM or even Chrome itself when making these blobs that has some sort of limitation and starts overwriting at a certain point. I'm trying to see if I can figure out a solution where I ensure the video is saved no matter what, but I am not sure how to go about it. I could automatically store the video in Drive every 10 minutes and then merge it all together, or somehow store it in your machine, but then I'd have to merge the pieces together somehow too. What I should be doing is obviously storing those in a server where I would then do all the processing, but video files are huge and it would be costly for me to do that, and it's a free extension so I can't really justify it. I'll see what I can do... :/

**Comment by Asheboy** [comment]
I'm experiencing 2 as well.

`Version 90.0.4430.11 (Official Build) dev (64-bit)`

**Comment by startupgurukul** [comment]
For issue 3 hope this helps https://github.com/jimmywarting/StreamSaver.js

**Comment by alyssaxuu** [comment]
I've implemented StreamSaver.js and this shouldn't be an issue anymore. The video will automatically download while recording, so no data can be lost.
