### ISSUE TITLE
hi I want ask something about navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by lanxisama** [alyssaxuu/screenity#41]
I use this api in  background.js like this :
`navigator.mediaDevices.getUserMedia({video: false,audio: true}).then(stream=>{}).catch(err=>{console.log(err)})`

But it always console log error If I want to get stream, do I need to do anything special?

Thanks Looking forward to your reply

**Comment by alyssaxuu** [comment]
Make sure you have the "desktopCapture" & "tabs" permission in the manifest, also in order to be able to record the screen from the background of an extension, I believe it needs a "user gesture", basically you can't start recording automatically, it needs to be triggered (the way I do it in my extension is through a button click on the popup that then sends a message to the background). If you're still experiencing problems, you could try to first request audio from a page within your extension, either a new dedicated page, or injecting that "page" through an iframe anywhere you want (which is what Screenity does), something like this: https://github.com/alyssaxuu/screenity/blob/master/js/audiosources.js

Anyway I'll close it since it's not relevant to Screenity but let me know if you have any more questions :)
