### ISSUE TITLE
Where shall I find the recorded files?

### ISSUE THREAD

**Issue by Rico-A** [alyssaxuu/screenity#44]
Hello,

Thank you for creating the extension. The descriptions sounds great, but I face the following challenges:

1.  I start to record and then share the application to be shared. The symbol for the extension turns from blue into red, but nothing else happens. I am also not able to "stop the recording" (in case that it even started). The symbol remains red until I disable or remove the extension and enable it again. Alt+S doesn't work either. How can I check that screenity is really recording and how can I stop the recording please?
2. Consequently, I also can't find any recordings nowhere. How shall I find the recorded files please? Where should the files be located or how can I access the recordings please?

Thank you & best regards,

Rico

**Comment by alyssaxuu** [comment]
Hi, are you attempting to record from a new tab/browser startup page (e.g. Google homepage), the Chrome Store, or an internal Chrome page? If so you won't be able to record, it only works in other pages (due to Chrome limitations). Alternatively it might be a permissions issue, if you're on Mac ([see here](https://github.com/alyssaxuu/screenity/issues/37)). Otherwise, do let me know the steps you're following so I can reproduce it and fix it for you (e.g. are you starting the recording from the popup, what settings so you have checked for the controls, do you have camera/microphone enabled, etc.) :)

**Comment by Rico-A** [comment]
Thank you for the quick response.

I am using the latest versions of Chrome @ Windows 10 and want to record the screen of QVR Pro (surveillance software). Therefore I activated screenity, click on the blue symbol, select “Desktop” and “record starting”. Then I choose the application (QVR Pro) and share it. Camera and microphone are deactivated. Resolution is 4K.

Meanwhile I was also able to record e. g. the “settings of Windows with screenity or create a printscreen of QVR Pro with the print key and clipboard (Win standard). However, recording QVR Pro Screenity either freeze while "loading..." or 1 time I got a video that has been empty and 0 kb after downloading.

Do you have any further advice what I could try to record QVR Pro?

**Comment by alyssaxuu** [comment]
> Thank you for the quick response.
> 
> I am using the latest versions of Chrome @ Windows 10 and want to record the screen of QVR Pro (surveillance software). Therefore I activated screenity, click on the blue symbol, select “Desktop” and “record starting”. Then I choose the application (QVR Pro) and share it. Camera and microphone are deactivated. Resolution is 4K.
> 
> Meanwhile I was also able to record e. g. the “settings of Windows with screenity or create a printscreen of QVR Pro with the print key and clipboard (Win standard). However, recording QVR Pro Screenity either freeze while "loading..." or 1 time I got a video that has been empty and 0 kb after downloading.
> 
> Do you have any further advice what I could try to record QVR Pro?

Hmmm that's odd. It seems like QVR Pro is using the screen sharing/recording functionality at the same time as Screenity, so Screenity is unable to get the stream (if it gets stuck on "Loading" & the popup doesn't close automatically, that's definitely what's happening). Not sure why it would be using such a thing though, maybe to prevent you from recording the surveillance footage? Printscreen should be fine because it's a completely different permission, not the same as screen sharing/recording.
