### ISSUE TITLE
Draw on canvas with camera only

### ISSUE THREAD

**Issue by Anil-matcha** [alyssaxuu/screenity#68]
Hi @alyssaxuu , not sure if this is the right place to ask but if you feel this doesn't belong here please close the issue.

I am trying to add a canvas to camera-only tab to allow drawing on top of the camera output similar to "Tab only" or "Desktop only". I injected a canvas element along with the video element and tried to draw on canvas element on a regular interval based on the input from camera. 

The issue I am facing is, the canvas always stays stuck at the first frame and the further frames from camera are not rendered. Here is a gist of camera.js file https://gist.github.com/Anil-matcha/6a5c4faa0a5a39510f6c4daf5325327b with few changes to include drawing on canvas. When I try running with it, the canvas always stays stuck. 

This issue happens only in the context of extension. If I try doing the same on a simple html page I don't see the issue of canvas getting stuck. It would be great if you can help me on this as to what's different here which leads to the canvas getting stuck.

**Comment by alyssaxuu** [comment]
The reason it's not rendering the canvas is because the MediaRecorder in that file is setup to record the camera feed directly, not the <video> HTML element itself (and whatever is in it). The way I would approach it is to render the video inside the canvas (here's a few ideas on how to do that: https://stackoverflow.com/questions/4429440/html5-display-video-inside-canvas/38711016), and then use the MediaRecorder to record the canvas itself (e.g. https://medium.com/@amatewasu/how-to-record-a-canvas-element-d4d0826d3591). You will need to keep re-rendering the canvas so that the video stream updates, so it might be a bit tricky to draw and make modifications - I recommend using Fabric.js for the canvas (which is what I'm using on Tab/Desktop recordings) which makes it simple.

**Comment by Anil-matcha** [comment]
Hi @alyssaxuu . Thanks a lot for responding. Currently I am not trying to record but was just trying to render on canvas to test. So what I have done is similar to the links you posted i.e take the data from video and draw on canvas periodically using setTimeout. But the problem I see is only the first frame is rendered and is stuck, the subsequent frames were not rendered. 

I tried to implement the same flow on a simple html page and it was working but in the context of chrome extension it was getting stuck. So wanted to check if there is something missing here which I am not able to see.

Also thanks a lot for pointing out Fabric.js, I will look into it.

**Comment by alyssaxuu** [comment]
You mean the first frame of the video? Are you getting any errors in the console? Can you check if the video itself is playing (so the video outside the canvas, not the one rendered inside)?

Otherwise, that would have to do with your method for rendering - make sure you clear the canvas on every re-render, you can also check if the rendering loop is actually working (or if it only renders once).

By working on an HTML page do you mean the exact same code, so with the live camera feed and the canvas, or in some other way?

**Comment by Anil-matcha** [comment]
Hi @alyssaxuu . Yes the first frame is rendered on the canvas, there are no errors which I am observing and the video is still playing in the background so it is not stopped. 

I tried clearing and updating canvas every time I render and also could see the rendering loop is running using logs but somehow the canvas is not updated

By html page I mean if I create a simple new web html project with the video and canvas tag and try to render on canvas the frames from video, I see no problem and it is working fine. So I was asking if there is some difference in the context of chrome extension which is preventing this from happening

**Comment by Anil-matcha** [comment]
For example this is a sample html demo doing the task of taking video frames and rendering on canvas https://peervadoo.com/canvas.html . If I try the same code in the context of chrome extension the canvas gets stuck at first frame

**Comment by alyssaxuu** [comment]
Hmmm that's strange. Maybe it depends on the page you're injecting from? I'm honestly not sure, maybe it's conflicting with other scripts or something.

**Comment by Anil-matcha** [comment]
Ok, thanks for looking into it. I will continue looking into it and will let you know of any updates. 

The advantage of being able to do this is adding snapchat kind of tools on top of webcam which can open up a lot more use-cases
