### ISSUE TITLE
Question: How to change google drive location

### ISSUE THREAD

**Issue by jjr284** [alyssaxuu/screenity#74]
Hi! I'd like to update the specified Google Drive folder location. Doe someone know how to do this? Thanks!

**Comment by alyssaxuu** [comment]
Screenity doesn't have this functionality, although if you're asking development-wise, it could easily be modified [here](https://github.com/alyssaxuu/screenity/blob/8b31d5e53265ecd55acf374294d2e9d42ce0f71e/js/videoeditor.js#L158) by adding the "parents" property in the metadata specifying a folder ID in Drive (API docs go in more detail [here](https://developers.google.com/drive/api/v3/folder#create_a_file_in_a_folder)). In order to make it work, you'd need to set up Google OAuth for the extension (through the Google Cloud Console), and update the "client_id" in the manifest, [here](https://github.com/alyssaxuu/screenity/blob/6c1863d4ef26f4a1919b77061e4dd59e4babc8cb/manifest.json#L14). The extension itself would also need its own unique key.

I don't personally think it's worth having a UI in Screenity to allow you to select a destination for the video. Then I'd also have to retrieve all the folders a user has which might require extra permissions and users might not be too happy about that either (from a privacy standpoint). Besides, the extension already opens the file after upload, and it can easily be moved elsewhere from there.

**Comment by NateDesmond** [comment]
I had a very similar request (mostly due to the ease of setting sharing settings on a single folder, rather than editing each video individually).

Following Alyssa's instructions, this is working great for me:
1. Download the full code as described in [Self-hosting Screenity](https://github.com/alyssaxuu/screenity#self-hosting-screenity)
2. Replace [row 158 in videoeditor.js](https://github.com/alyssaxuu/screenity/blob/8b31d5e53265ecd55acf374294d2e9d42ce0f71e/js/videoeditor.js#L158) with these two lines of code:
```
                mimeType: 'video/mp4',
                parents: 'your-desired-folder-id' // Get this from your folder URL: https://drive.google.com/drive/u/folders/your-desired-folder-id
```

**Comment by NateDesmond** [comment]
I had a very similar request (mostly due to the ease of setting sharing settings on a single folder, rather than editing each video individually).

Following Alyssa's instructions, this is working great for me:
1. Download the full code as described in [Self-hosting Screenity](https://github.com/alyssaxuu/screenity#self-hosting-screenity)
2. Replace [row 158 in videoeditor.js](https://github.com/alyssaxuu/screenity/blob/8b31d5e53265ecd55acf374294d2e9d42ce0f71e/js/videoeditor.js#L158) with these two lines of code:
```
                mimeType: 'video/mp4',
                parents: 'your-desired-folder-id' // Get this from your folder URL: https://drive.google.com/drive/u/folders/your-desired-folder-id
```
3. Update the client_id in [manifest.json line 14](https://github.com/alyssaxuu/screenity/blob/master/manifest.json#L14)
4. Complete [steps 2-4 on Self-Hosting](https://github.com/alyssaxuu/screenity#self-hosting-screenity)

One question for Alyssa: Is it important that we create a separate client_id, or is it fine to use the one you've got in the core extension?

I've also gone a step further, and programmed my version to find or create a Drive folder named "Screenity Videos" and then save to that location. Alyssa, I'm not sure whether this is something you'd find useful in the main extension, but if so I'd be happy to create a pull request.

**Comment by alyssaxuu** [comment]
> I had a very similar request (mostly due to the ease of setting sharing settings on a single folder, rather than editing each video individually).
> 
> Following Alyssa's instructions, this is working great for me:
> 
> 1. Download the full code as described in [Self-hosting Screenity](https://github.com/alyssaxuu/screenity#self-hosting-screenity)
> 2. Replace [row 158 in videoeditor.js](https://github.com/alyssaxuu/screenity/blob/8b31d5e53265ecd55acf374294d2e9d42ce0f71e/js/videoeditor.js#L158) with these two lines of code:
> 
> ```
>                 mimeType: 'video/mp4',
>                 parents: 'your-desired-folder-id' // Get this from your folder URL: https://drive.google.com/drive/u/folders/your-desired-folder-id
> ```
> 
> 1. Update the client_id in [manifest.json line 14](https://github.com/alyssaxuu/screenity/blob/master/manifest.json#L14)
> 2. Complete [steps 2-4 on Self-Hosting](https://github.com/alyssaxuu/screenity#self-hosting-screenity)
> 
> One question for Alyssa: Is it important that we create a separate client_id, or is it fine to use the one you've got in the core extension?
> 
> I've also gone a step further, and programmed my version to find or create a Drive folder named "Screenity Videos" and then save to that location. Alyssa, I'm not sure whether this is something you'd find useful in the main extension, but if so I'd be happy to create a pull request.

Nice :) The client_id is linked to the extension key, so it can only be used for that. If one wants to self-host they should create a unique key for their extension version and in turn a client_id for it.

That might be good to have yeah. I've had several people ask for it, I guess it's also good for organization.

**Comment by ashiktalukdar069** [comment]
Nice
