### ISSUE TITLE
Add linting and prettier formatting

### ISSUE THREAD

**Issue by njelich** [alyssaxuu/screenity#76]
Linting makes our lives easier because it tells us what’s wrong with our code. Prettier makes formatting universal, and easier to follow.

Adding these would make collaboration easier in the long term.

**Comment by alyssaxuu** [comment]
It's something I might consider. Then again I see Screenity more as a personal project that I've made open source for people to remix and make their own versions out of rather than a collaborative project where people contribute and improve upon. Just thought it would be nice to share the code so people can make their own screen recorders, and also so people can self host (if they're concerned about privacy).

**Comment by alyssaxuu** [comment]
Added in the new MV3 version.
