### ISSUE TITLE
Video doesn't play

### ISSUE THREAD

**Issue by egoist** [alyssaxuu/screenity#8]
![image](https://user-images.githubusercontent.com/8784712/99881956-f179cb80-2c57-11eb-8e7c-48c95fa9e593.png)

When I finish recoding it opens this page but the video doesn't play and there's an error you can see above. Tried in both Edge and Chrome, still no luck.

**Comment by egoist** [comment]
Somehow it's working now, closing ;D

**Comment by alyssaxuu** [comment]
Glad it's working, it could be a memory issue though (especially if it was a long recording). I added an option in the popup menu to reduce the memory used when recording, since some computers might not be able to handle HQ recordings.

<img width="344" alt="Screen Shot 2020-11-21 at 5 18 53 PM" src="https://user-images.githubusercontent.com/7581348/99882015-a347d680-2c1d-11eb-8e21-5483128d20ba.png">
