### ISSUE TITLE
Doesn't load when viewing PDF or other files on local disk

### ISSUE THREAD

**Issue by tekumara** [alyssaxuu/screenity#88]
Stuck on `Loading...`

**Comment by tekumara** [comment]
Works when viewing PDFs over HTTP

**Comment by alyssaxuu** [comment]
That seems likely to be some copy protection issue if it works when viewing other applications. It likely can't be recorded using any other program. Closing since it's not something I could override on my end (maybe there's some permission setting you can set so that pdfs can be recorded, not sure).
