### ISSUE TITLE
Recording from browser without chrome extension similar to loom

### ISSUE THREAD

**Issue by Anil-matcha** [alyssaxuu/screenity#90]
Can we use screenity to record camera+screen without the need for installing a chrome extension ? Loom allows to record directly from browser with the click of a button without needing an extension. Can something like this be possible with screenity ?

**Comment by alyssaxuu** [comment]
Without an extension it could certainly record the screen and camera, but it wouldn't be able to inject controls onto any page or allow you to annotate, which is sort of the whole idea of Screenity :P

**Comment by Anil-matcha** [comment]
@alyssaxuu  Thanks a lot for replying. Loom just released an sdk for public use which allows to launch recording and injection options at the click of a button. https://www.producthunt.com/posts/loomsdk-beta it is the producthunt product of the day. 

So ideally wouldn't it be possible that we can do all things screenity does without needing an extension ?

**Comment by alyssaxuu** [comment]
This SDK is meant so that companies can integrate Loom into their products, it's for specific use cases. Yes you can use Screenity in a * specific * page (without an extension) where controls and camera can show up, but it cannot extend beyond that page. I could certainly also build some sort of SDK similar to Loom if companies want to have Screenity in their products for whatever purpose (e.g. so that users can report bugs or share feedback related to a specific app in video format), but it would deviate from what the concept and audience of Screenity is. And again this would not be aimed towards the average user who wants to record and annotate their screen for whatever purpose, this would be aimed towards companies who need tools to report bugs, feedback, etc.

**Comment by Anil-matcha** [comment]
@alyssaxuu  Thanks for taking time to reply. That is pretty comprehensive information you shared. Love the work you are doing in the open-source community. Closing this ticket for now
